- name: Check if vscode is installed
  changed_when: false
  failed_when: false
  ansible.builtin.command: command -v code
  register: code_installed

- name: Install VS Code
  when: code_installed.rc != 0
  become: true
  community.general.pacman:
    state: latest
    name: code

- name: Install code-marketplace
  kewlfft.aur.aur:
    state: latest
    name: code-marketplace

- name: Get installed extensions
  ansible.builtin.command: code --list-extensions
  register: installed_extensions
  changed_when: false

- name: Install extensions
  ansible.builtin.command: "code --install-extension {{ item }}"
  with_items: "{{ vscode_extensions }}"
  when: "item not in installed_extensions.stdout"
  changed_when: true
