- name: Install typst
  become: true
  community.general.pacman:
    state: latest
    name:
      - rust
      - typst
      - typst-lsp

- name: Install VS Code extension
  ansible.builtin.command: code --install-extension myriad-dreamin.tinymist
  changed_when: true
