- name: Check if dotter is installed
  changed_when: false
  ansible.builtin.command: dotter --version
  register: dotter_installed

- name: Install dotter
  when: dotter_installed.rc != 0
  kewlfft.aur.aur:
    state: latest
    name: dotter-rs-bin


- name: Create local.toml
  ansible.builtin.copy:
    mode: '644'
    dest: "{{ playbook_dir }}/../dotfiles/.dotter/local.toml"
    content: |
      includes = [".dotter/default.toml"]
      packages = ["default"]

- name: Deploy using dotter
  ansible.builtin.command: dotter deploy --force
  args:
    chdir: "{{ playbook_dir }}/../dotfiles"
  changed_when: true
