[git.files]
gitconfig = "~/.gitconfig"

[kde.variables]
kde_cmds = [
  "kwriteconfig6 --file kdeglobals --group KDE --key SingleClick true",
]

[kde.files]
"kde/dolphin/view" = "~/.local/share/dolphin/view_properties/global/.directory"
"kde/dolphin/rc" = "~/.config/dolphinrc"
"kde/konsole/rc" = "~/.config/konsolerc"
"kde/konsole/zsh_profile" = "~/.local/share/konsole/zsh.profile"
"kde/kcminputrc" = "~/.config/kcminputrc"
"kde/krunnerrc" = "~/.config/krunnerrc"
"kde/ksmserverrc" = "~/.config/ksmserverrc"
"kde/kscreenlockerrc" = "~/.config/kscreenlockerrc"
"kde/feedback" = "~/.config/PlasmaUserFeedback"

[vscode.files]
"vscode/settings.json" = "~/.config/Code/User/settings.json"
"vscode/keybindings.json" = "~/.config/Code/User/keybindings.json"

[zsh.files]
"zsh/rc" = "~/.zshrc"
"zsh/p10k" = "~/.p10k.zsh"
"zsh/plugins" = "~/.zsh_plugins.txt"
