- name: Collection of extra roles that can be run ad-hoc
  hosts: localhost
  roles:
    # Prevent playbook execution by mistake
    - stop_playbook

    # Tagged ad-hoc roles
    - role: ansible_dev
      tags: [ansible]
    - role: bcsfe
      tags: [bcsfe]
