- name: Collection of extra roles that can be run ad-hoc
  hosts: localhost
  roles:
    # Prevent playbook execution by mistake
    - stop_playbook

    # Tagged ad-hoc roles
    - role: ansible_dev
      tags: [ansible]
    - role: bcsfe
      tags: [bcsfe]
    - role: dotfiles
      tags: [dotfiles]
    - role: lts_kernel
      tags: [kernel]
    - role: typst
      tags: [typst]
    - role: vscode
      tags: [vscode]
    - role: zsh
      tags: [zsh]
