- name: Provision EndeavourOS Virtual Machines
  hosts: localhost
  roles:
    - role: lts_kernel
      tags: [kernel]
    - role: packages
      tags: [packages, yay]
    - role: vscode
      tags: [vscode]
    - role: zsh
      tags: [zsh]
    - role: dotfiles
      tags: [dotfiles]
