- name: Provision EndeavourOS Virtual Machines
  hosts: localhost
  roles:
    - role: lts_kernel
      tags: [kernel]
    - role: packages
      tags: [packages, yay]
      vars:
        packages_add_extra: "{{ packages_add_vm }}"
        packages_rem_extra: "{{ packages_rem_vm }}"
    - role: vscode
      tags: [vscode]
    - role: zsh
      tags: [zsh]
    - role: dotfiles
      tags: [dotfiles]
